Wir beginnen damit, unsere Matrizen von Hand einzugeben und die ersten Rechnungen nachzuvollziehen

In [1]:
import numpy as np

A1 = np.array([ [5,2,0], [1,4,5], [-5,4,-3] ])
A1

array([[ 5,  2,  0],
       [ 1,  4,  5],
       [-5,  4, -3]])

In [2]:
M1 = np.array([ [1,0,0], [-1./5,1,0], [1,0,1] ])
M1

array([[ 1. ,  0. ,  0. ],
       [-0.2,  1. ,  0. ],
       [ 1. ,  0. ,  1. ]])

In [3]:
A2 = M1.dot(A1)
A2

array([[ 5. ,  2. ,  0. ],
       [ 0. ,  3.6,  5. ],
       [ 0. ,  6. , -3. ]])

Einschub: Alternativ zu der Eingabe von Hand können wir auch M1 "geschickt" berechnen

In [4]:
l1 = np.array([[0, 1./5, -1]])
e1_t = np.array([[1,0,0]])

M1b = np.identity(3)-l1.T.dot(e1_t)
M1b

array([[ 1. ,  0. ,  0. ],
       [-0.2,  1. ,  0. ],
       [ 1. ,  0. ,  1. ]])

In [5]:
np.linalg.norm(M1 - M1b)

0.0

Nach demselben Schema berechnen wir nun M2

In [6]:
l2 = np.array([[0, 0, 6/3.6]])
e2_t = np.array([[0,1,0]])

M2 = np.identity(3)-l2.T.dot(e2_t)
M2

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        , -1.66666667,  1.        ]])

In [7]:
A3 = M2.dot(A2)
A3

array([[  5.        ,   2.        ,   0.        ],
       [  0.        ,   3.6       ,   5.        ],
       [  0.        ,   0.        , -11.33333333]])

Damit haben wir U! L wird jetzt noch berechnet

In [8]:
U = A3
Ltilde = M2.dot(M1)

In [9]:
L = np.linalg.inv(Ltilde)
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.2       ,  1.        ,  0.        ],
       [-1.        ,  1.66666667,  1.        ]])

...Und wir kontrollieren

In [10]:
L.dot(U)

array([[ 5.,  2.,  0.],
       [ 1.,  4.,  5.],
       [-5.,  4., -3.]])

In [11]:
A1

array([[ 5,  2,  0],
       [ 1,  4,  5],
       [-5,  4, -3]])

# Anwendungen

## Det berechnen

In [12]:
np.linalg.det(A1)

-203.99999999999994

In [13]:
U[0,0]*U[1,1]*U[2,2]

-203.99999999999997

## Löse ein Gleichungssystem

In [14]:
def vorwaertseinsetzen(A, b):
    x = np.zeros(len(b))
    for j in range(len(b)):
        inner_sum = 0
        for k in range(j):
            inner_sum += A[j, k]*x[k]
        x[j] = 1./A[j,j]*(b[j] - inner_sum)
    return x

In [15]:
from rueckweins import rueckwaertseinsetzen

In [16]:
b = np.array([9,4,6])

In [17]:
np.linalg.solve(A1,b)

array([ 1.,  2., -1.])

In [18]:
z = vorwaertseinsetzen(L,b)
x = rueckwaertseinsetzen(U,z)
x

array([ 1.,  2., -1.])

## Inverse bestimmen

In [19]:
goal = np.linalg.inv(A1)
goal

array([[ 0.15686275, -0.02941176, -0.04901961],
       [ 0.10784314,  0.07352941,  0.12254902],
       [-0.11764706,  0.14705882, -0.08823529]])

In [20]:
k = 0

e_k = np.zeros(3)
e_k[k] = 1

e_k
rueckwaertseinsetzen(U,vorwaertseinsetzen(L,e_k))

array([ 0.15686275,  0.10784314, -0.11764706])

In [21]:
goal2 = np.zeros((3,3))
goal2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
for k in range(3):
    e_k = np.zeros(3)
    e_k[k] = 1

    z = rueckwaertseinsetzen(U,vorwaertseinsetzen(L,e_k))
    for i in range(3):
        goal2[i, k] = z[i]

In [23]:
goal2

array([[ 0.15686275, -0.02941176, -0.04901961],
       [ 0.10784314,  0.07352941,  0.12254902],
       [-0.11764706,  0.14705882, -0.08823529]])

In [24]:
np.linalg.norm(goal-goal2)

4.443059973708341e-17

# Invertieren von Ltilde

In [26]:
# Bisher hatten wir gerechnet...
M1 = np.identity(3)-l1.T.dot(e1_t)
print("M1: ", M1)
M2 = np.identity(3)-l2.T.dot(e2_t)
print("M2: ", M2)

Ltilde = M2.dot(M1)
print("Ltilde: ", Ltilde)
L = np.linalg.inv(Ltilde)
print("L: ", L)

M1:  [[ 1.   0.   0. ]
 [-0.2  1.   0. ]
 [ 1.   0.   1. ]]
M2:  [[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.         -1.66666667  1.        ]]
Ltilde:  [[ 1.          0.          0.        ]
 [-0.2         1.          0.        ]
 [ 1.33333333 -1.66666667  1.        ]]
L:  [[ 1.          0.          0.        ]
 [ 0.2         1.          0.        ]
 [-1.          1.66666667  1.        ]]


In [28]:
M1inv = np.identity(3)+l1.T.dot(e1_t)

print(M1inv.dot(M1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
M2inv = np.identity(3)+l2.T.dot(e2_t)

print(M2inv.dot(M2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
Lb = M1inv.dot(M2inv)
Lb

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.2       ,  1.        ,  0.        ],
       [-1.        ,  1.66666667,  1.        ]])

In [34]:
np.linalg.norm(Lb - L)

0.0